### PR TITLE
Add spreadsheet-actions.js extensions, with support for inserting/del…

### PR DESCRIPTION
**Pull request by edigeronimo**
…eting columns/rows, similar to what you would find in spreadsheet software

### CODE REVIEW

**Comment by eishiya** [comment]
Since this is one of my scripts, perhaps it should be in my Tiled scripts repo rather than here? I didn't upload it because I didn't feel it was useful to anyone else.

**Comment by bjorn** [comment]
I agree this would be better shared through @eishiya's own Tiled scripts repository, which is already linked from the `README.md`.

**Comment by edigeronimo** [comment]
Share it however. I did it this way as Bjorn suggested it in Discord. Share my version tho, as I made a few improvements over eishiya's initial version. Share it tho! It's such a massive timesaver for tuning platfomer levels.

**Comment by eishiya** [comment]
Done: https://github.com/eishiya/tiled-scripts/blob/main/SpreadsheetActions.js
I merged your getObjectLayers function into the existing getMapLayers function, there's no reason to iterate all the layers twice. I also made the object-shifting optional, since it doesn't work correctly for staggered maps and since not everyone's objects are tied to the tile layout. If I get bored one day in the future, I might look into making it work correctly for staggered maps as well.
Lastly, I made the script respect layer locks - at least when the API cooperates and returns the correct value for layer.locked, which it doesn't always xP

Thanks again for your additions!

**Pull request closed without merging**
