### PR TITLE
Add linter check

### PR DESCRIPTION
**Pull request by diogoeichert**
New approach, based on our last conversation:

- adds the linter
- adds automatic check in the pipeline (to avoid indentation issues like in my previous PR, for example)
- conforms to the linter rules in a more conservative way (e.g. commenting unused parameters instead of removing them)

From my perspective, the main value of this change is to adopt a linting standard that can help with the "robustness" of the JS extensions, and then forget about it. It should be automatically handled by editors compatible with `eslint` (VS Code, for example) and also prevent non-formatted code from event taking up PR review time, since the pipeline should already raise warnings about mis-indentation, etc. (even so that I could have actually omitted the README.md entry).

About the braces, here I come with [yet another article](https://exceptionshub.com/are-curly-braces-necessary-in-one-line-statements-in-javascript.html) that tries to illustrate the kinds of issues that can be avoided by always using them. It can be still a matter of taste, but I'd say using them means staying in the safe side of the balance.

Bonus: with the addition of the npm package*.json files, it should be also straightforward to keep these linting tools up to date.

### CODE REVIEW

**Comment by bjorn** [comment]
> About the braces, here I come with [yet another article](https://exceptionshub.com/are-curly-braces-necessary-in-one-line-statements-in-javascript.html) that tries to illustrate the kinds of issues that can be avoided by always using them. It can be still a matter of taste, but I'd say using them means staying in the safe side of the balance.

I was wondering if there was some JavaScript-specific reason to always write those braces. I've been coding in C++ for over 20 years now and I've contributed to a huge project (Qt) that has in [its coding style rules](https://wiki.qt.io/Qt_Coding_Style#Braces) the rule to "Use curly braces only when the body of a conditional statement contains more than one line". The rule exists plainly for readability, with two exceptions that also serve mostly readability.

I haven't seen a good argument to write them. It appears to me mostly about ambiguous `else` and bugs due to adding more code later, but in both cases the body becomes more than one line, at which point you'll add the braces and all is fine.

Anyway, if this is how people want to code in "standard JS", then let's have it.

Btw, you still need to find a way to tell GitHub that those tabs are supposed to be only 4 spaces, because as it is the 8-spaces indentation is way too much.

**Comment by diogoeichert** [comment]
It's your call, I can share [still one more good reason to avoid missing the braces](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/). I'm not sure we can change the way GitHub displays the tabs, though. I tried to contact their support, but it seems only business / premium customer have that channel available. Anyways, if you think this is too much of a change, we can just drop this PR.

**Comment by bjorn** [comment]
@diogoeichert Did you notice the PR I sent you to add the `.editorconfig` to this PR?

**Comment by diogoeichert** [comment]
@bjorn Thanks for letting me know, I didn't get any kind of notification from GitHub about this. Merged.

**Comment by bjorn** [comment]
Hmm, these tabs still appear to cause weird display issues:

image

I guess that is only to be expected. Also, the `.editorconfig` file does not appear to affect all .js files when I look at the diff (`rectangle-chain.js` is still indenting with huge 8-space tabs).

Anyway, let's try this for a while. If it keeps causing issues we can always switch back to using spaces.

**Comment by bjorn** [comment]
Thanks for your efforts to ensure this repository contains clean JS code, @diogoeichert!

**Pull request merged**
