### PR TITLE
Add linter

### PR DESCRIPTION
**Pull request by diogoeichert**
Adds eslint, runs it with --fix (to automatically fix indentation issues), declare globals to avoid linter warnings and removes unused variables detected by the linter. I recommend reviewing the pull request ignoring whitespace changes for better clarity.

### CODE REVIEW

**Comment by bjorn** [comment]
Hmm, can we tell the linter to avoid the insertion of superfluous semicolons? Also, if there is only one statement in a conditional body I'd prefer to leave out the braces. Or is there some reason to have them anyway?

**Comment by diogoeichert** [comment]
> Hmm, can we tell the linter to avoid the insertion of superfluous semicolons? Also, if there is only one statement in a conditional body I'd prefer to leave out the braces. Or is there some reason to have them anyway?

There are actually a few good reasons to keep the semicolons in JS, there are known issues when JavaScript is minified and also debugging might be more difficult in some cases (more about that [here](https://dev.to/adriennemiller/semicolons-in-javascript-to-use-or-not-to-use-2nli)). The braces are in a similar situation, it's easier to get confused when they're absent and to miss them if you ever need to add more statements in the existing condition block. I tried to come up with a minimalistic list for the reasons behind every linter rule [here](https://github.com/diogoeichert/eslint-config-standard-js), but it still needs work. They should give the big picture, though and at a personal level I feel enforcing these cause less pain in the long run.

**Comment by bjorn** [comment]
Hmm, all the removed "unused variables" seem to have been function parameters, which I'd definitely want to include, mainly for documentation purposes. Leaving them out suggests that the callbacks don't receive those parameters.

Regarding the semicolons, the minification argument doesn't really work but I can see there's apparently quite some support in the JS community for always writing them, so that's alright.

About enforced braces, it's not my coding style and I personally find leaving out those needless braces often helps with readability, but I'm fine with having them in these JS snippets.

**Comment by diogoeichert** [comment]
> Hmm, all the removed "unused variables" seem to have been function parameters, which I'd definitely want to include, mainly for documentation purposes. Leaving them out suggests that the callbacks don't receive those parameters.
> 
> Regarding the semicolons, the minification argument doesn't really work but I can see there's apparently quite some support in the JS community for always writing them, so that's alright.
> 
> About enforced braces, it's not my coding style and I personally find leaving out those needless braces often helps with readability, but I'm fine with having them in these JS snippets.

I was actually thinking about the unused parameters in the function signatures as "documentation code" as I was removing them. I guess it would be nicer to just comment them out, then. Let me try a different approach to the linter fixes, then you can reevaluate if it makes sense.

**Comment by diogoeichert** [comment]
This branch got unclean because I created it before the previous one was merged. I'll close this PR, and open a new PR from a clean fork instead.

**Comment by bjorn** [comment]
You could have rebased the branch. :-)

**Comment by diogoeichert** [comment]
I did but I forgot to set the upstream in the fork to the original repo. 😛

**Pull request closed without merging**
